Repository conduktor/conduktor-public-charts, pull requests merged in 2025-03, with the labels that each got.

#164 feat(Gateway):Add small shortcut to chart values
  charts/gateway/README.md
  charts/gateway/templates/NOTES.txt
  charts/gateway/templates/_helpers.tpl
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/prometheus-monitoring.yaml
  charts/gateway/templates/secrets.yaml
  charts/gateway/templates/tests/01-gateway-healthy.yaml
  charts/gateway/values.yaml
Labels: enhancement

#154 [Gateway] Remove Kafka dependency
  .github/workflows/chart-test.yaml
  Makefile
  README.md
  charts/gateway/Chart.lock
  charts/gateway/Chart.yaml
  charts/gateway/README.md
  charts/gateway/ci/01-basic-gateway-required-values.yaml
  charts/gateway/ci/02-gateway-with-selfSigned-ingress-values.yaml
  charts/gateway/templates/NOTES.txt
  charts/gateway/templates/_helpers.tpl
  charts/gateway/templates/deployment.yaml
  charts/gateway/templates/tests/01-setup-dependency.yaml
  charts/gateway/templates/tests/02-gateway-healthy.yaml
  charts/gateway/values.yaml
Labels: bug, breaking

#167 [Gateway] Add support for extraDeploy on Gateway chart
  charts/gateway/README.md
  charts/gateway/templates/extra-deploy.yaml
  charts/gateway/values.yaml
Labels: enhancement

#168 [Gateway] Move resources definition to gateway value block
  charts/gateway/README.md
  charts/gateway/templates/NOTES.txt
  charts/gateway/templates/deployment.yaml
  charts/gateway/values.yaml
Labels: documentation, enhancement

#175 fix(Gateway): fix duplicate GATEWAY_SECURED_METRICS env
  charts/gateway/templates/_helpers.tpl
  charts/gateway/templates/deployment.yaml
Labels: bug
